[green_agent]
endpoint = "http://127.0.0.1:9009"

[[participants]]
role = "purple_agent"
endpoint = "http://127.0.0.1:9002"

[config]
num_tasks = 1
mcp_enabled = true
tasks_file = "data/fhiragentbench_tasks.csv"
max_iterations = 10
max_concurrent = 3
