[green_agent]
endpoint = "http://127.0.0.1:9000"

[[participants]]
role = "purple_agent"
endpoint = "http://127.0.0.1:9001"

[config]
num_tasks = 10
mcp_enabled = false
tasks_file = "data/test.csv"
max_iterations = 10
max_concurrent = 1
